portrayal:
  units:
    "@atools/portrayal-units-recent-posts":
      yuque:
        includeRepos:
          - "ct"
          - "chatgpt"
          - "qifu"
          - "code-and-art"
          - "chatgpt"
      blog:
        atomOrFeedsUrl: "https://xiaoa.name/feed.xml"

  cards:
    "@atools/portrayal-cards-recent-posts":
      two-column-github-profile:
        left:
          emoji: 🧪
          title: "Digital Garden"
          link: "https://www.yuque.com/chiyu-heb0t"
        right:
          emoji: 🌈
          title: "Blog"
          link: "https://xiaoa.name/blog"
