# This is a basic workflow that is manually triggered

name: Dispatch Github Profile Update

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      yuque_token:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Yuque Token'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate-portrayal:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Npm install
      run: npm install -g @atools/portrayal@beta
    - name: Generate
      run: rm -rf ./.portrayal && YUQUE_TOKEN="${{ inputs.yuque_token }}" pt ge
    - name: Update readme
      run: |-
        npm install
        node ./scripts/update-me.js
        cat README.md
    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "qddegtya@gmail.com"
        git config --global user.name "qddegtya-bot"
        git pull
        git add -A
        git commit -m "Updated content" || exit 0
        git push
